service: Employe-Certification-Get-API
provider:
  name: aws
  region: ap-south-1
  runtime: nodejs18.x
  stage: dev
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.EmployeCertificationTable}
custom:
  EmployeCertificationTable: EmployeeDetailsTable
plugins:
  - serverless-iam-roles-per-function
functions: 
  getDetail:
    handler: app.getCertificates
    name: get-Certificates
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee/{empID}
          method: GET
          cors: true
      - http:
          method: GET
          path: employees
          cors: true    
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
          - "dynamodb:Scan"  # Add this line to grant Scan permission
        Resource: !GetAtt EmployCertificate.Arn
  deleteSkillInfo: 
    handler: app.deleteEmployeeSkillInfo
    name: delete-EmployeeSkillInfo
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: employee/{empID}
          method: DELETE
          cors: true
    iamRoleStaments: 
      - Effect: "Allow"
        Action: 
          - "dynamodb:DeleteItem"
        Resource: !GetAtt EmployCertificate.Arn
  softDeleteSkillInfo: 
    handler: app.softDeleteEmployeeSkillInfo
    name: soft-delete-EmployeeSkillInfo
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: employee/{empID}/softDelete
          method: DELETE
          cors: true
    iamRoleStaments: 
      - Effect: "Allow"
        Action: 
          - "dynamodb:UpdateItem"
        Resource: !GetAtt EmployCertificate.Arn
resources: 
  Resources:
    EmployCertificate: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.EmployeCertificationTable}
        AttributeDefinitions:
          - AttributeName: empID
            AttributeType: S
        KeySchema: 
         - AttributeName: empID
           KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
